const state={signals:[],filters:{country:'all',category:'all',confidence:0}};
const $=s=>document.querySelector(s);
const riskFor=items=>{if(!items.length)return 0;const raw=items.reduce((sum,s)=>sum+s.impact*(s.confidence/100),0)/items.length;return Math.round(Math.min(100,raw*1.25));};
const riskClass=v=>v>=70?'high':v>=45?'medium':'low';
const priorityFor=s=>Math.round((s.impact*.6)+(s.confidence*.4));
const unique=key=>[...new Set(state.signals.map(s=>s[key]))].sort((a,b)=>a.localeCompare(b,'ru'));
function fillSelect(selector,values){const select=$(selector);values.forEach(value=>{const option=document.createElement('option');option.value=value;option.textContent=value;select.append(option);});}
function filtered(){return state.signals.filter(s=>(state.filters.country==='all'||s.country===state.filters.country)&&(state.filters.category==='all'||s.category===state.filters.category)&&s.confidence>=state.filters.confidence);}
function renderMetrics(items){const countries=new Set(items.map(s=>s.country));const risks=[...countries].map(country=>riskFor(items.filter(s=>s.country===country)));$('#signalCount').textContent=items.length;$('#countryCount').textContent=countries.size;$('#averageRisk').textContent=risks.length?`${Math.round(risks.reduce((a,b)=>a+b,0)/risks.length)}/100`:'—';$('#highPriorityCount').textContent=items.filter(s=>priorityFor(s)>=70).length;}
function renderCountries(items){const root=$('#countryCards');root.replaceChildren();const countries=unique('country').filter(country=>items.some(s=>s.country===country));if(!countries.length){root.append($('#emptyState').content.cloneNode(true));return;}countries.forEach(country=>{const signals=items.filter(s=>s.country===country);const risk=riskFor(signals);const card=document.createElement('article');card.className='country-card';card.innerHTML=`<div class="country-top"><div><div class="country-name">${country}</div><div class="muted">${signals[0].code}</div></div><div class="risk ${riskClass(risk)}">${risk}</div></div><div class="bar"><span style="width:${risk}%"></span></div><div class="country-meta"><span>${signals.length} сигнал(а)</span><span>уверенность ${Math.round(signals.reduce((a,s)=>a+s.confidence,0)/signals.length)}%</span></div>`;root.append(card);});}
function renderFeed(items){const root=$('#signalFeed');root.replaceChildren();$('#visibleCount').textContent=`Показано: ${items.length}`;if(!items.length){root.append($('#emptyState').content.cloneNode(true));return;}[...items].sort((a,b)=>b.date.localeCompare(a.date)||priorityFor(b)-priorityFor(a)).forEach(s=>{const priority=priorityFor(s);const row=document.createElement('article');row.className='signal';row.innerHTML=`<div><div class="signal-date">${new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(s.date))}</div><div class="signal-source">${s.source}</div></div><div><div class="signal-title">${s.title}</div><div class="signal-summary">${s.summary}</div><div class="badges"><span class="badge">${s.country}</span><span class="badge">${s.category}</span><span class="badge">уверенность ${s.confidence}%</span><span class="badge">влияние ${s.impact}%</span></div></div><div class="priority"><strong class="risk ${riskClass(priority)}">${priority}</strong>приоритет</div>`;root.append(row);});}
function render(){const items=filtered();renderMetrics(items);renderCountries(items);renderFeed(items);}
function bind(){$('#countryFilter').addEventListener('change',e=>{state.filters.country=e.target.value;render();});$('#categoryFilter').addEventListener('change',e=>{state.filters.category=e.target.value;render();});$('#confidenceFilter').addEventListener('input',e=>{state.filters.confidence=Number(e.target.value);$('#confidenceValue').textContent=`${e.target.value}%`;render();});$('#resetFilters').addEventListener('click',()=>{state.filters={country:'all',category:'all',confidence:0};$('#countryFilter').value='all';$('#categoryFilter').value='all';$('#confidenceFilter').value=0;$('#confidenceValue').textContent='0%';render();});}
async function init(){try{const response=await fetch('data/signals.json');if(!response.ok)throw new Error(`HTTP ${response.status}`);const data=await response.json();state.signals=data.signals;fillSelect('#countryFilter',unique('country'));fillSelect('#categoryFilter',unique('category'));$('#updatedAt').textContent=`Срез: ${new Intl.DateTimeFormat('ru-RU',{dateStyle:'medium',timeStyle:'short'}).format(new Date(data.generatedAt))}`;bind();render();}catch(error){console.error(error);$('#signalFeed').innerHTML='<div class="empty">Не удалось загрузить данные. Запустите проект через локальный HTTP-сервер.</div>';}}
init();